[project]
name = "sentiment-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.0",
    "scikit-learn>=1.7.0",
    "tensorflow[and-cuda]==2.17",
]
